import { TableNode, EnumType } from './store';
import { Edge } from '@xyflow/react';

export function generateSQL(nodes: TableNode[], edges: Edge[], enums: EnumType[] = []): string {
    const dropTables = nodes.map(n => `DROP TABLE IF EXISTS "${n.data.name}" CASCADE;`).join('\n');
    const dropTypes = enums.map(e => `DROP TYPE IF EXISTS "${e.name}" CASCADE;`).join('\n');

    const enumDefs = enums.map(e => {
        const values = e.values.map(v => `'${v}'`).join(', ');
        return `CREATE TYPE "${e.name}" AS ENUM (${values});`;
    });

    const tables = nodes.map((node) => {
        const { name, columns } = node.data;
        const columnDefs = columns.map((col) => {
            let type = col.type;

            // Map common types
            if (type === 'int') type = 'INTEGER';
            if (type === 'bool') type = 'BOOLEAN';

            // Add length/precision/scale if present
            if (col.length !== undefined && col.length !== null && !isNaN(Number(col.length))) {
                if (col.scale !== undefined && col.scale !== null && !isNaN(Number(col.scale))) {
                    type += `(${col.length}, ${col.scale})`;
                } else {
                    type += `(${col.length})`;
                }
            }

            // Handle Array
            if (col.isArray) {
                type += '[]';
            }

            let def = `  "${col.name}" ${type}`;
            if (col.isPk) def += ' PRIMARY KEY';
            if (!col.isNullable && !col.isPk) def += ' NOT NULL';
            if (col.isUnique && !col.isPk) def += ' UNIQUE';

            if (col.defaultValue) {
                // Simple heuristic to check if it's a number or function/boolean, otherwise quote it
                const isNumOrFunc = /^-?\d+(\.\d+)?$/.test(col.defaultValue) ||
                    col.defaultValue.toUpperCase().includes('CURRENT_TIMESTAMP') ||
                    col.defaultValue.toUpperCase() === 'TRUE' ||
                    col.defaultValue.toUpperCase() === 'FALSE' ||
                    col.defaultValue.toUpperCase() === 'NULL';

                def += ` DEFAULT ${isNumOrFunc ? col.defaultValue : `'${col.defaultValue}'`}`;
            }

            return def;
        });

        // Foreign Keys from edges
        const constraints: string[] = [];

        // Find edges where this table is the TARGET (the one having the FK)
        edges.filter(e => e.target === node.id).forEach(edge => {
            // The FK column is on this table (targetHandle)
            const targetHandle = edge.targetHandle;
            if (!targetHandle) return;

            const colId = targetHandle.replace('-target', '');
            const col = columns.find(c => c.id === colId);

            // Find referenced table (source) and its column
            const sourceNode = nodes.find(n => n.id === edge.source);
            if (!sourceNode || !edge.sourceHandle) return;

            const sourceColId = edge.sourceHandle.replace('-source', '');
            const sourceCol = sourceNode.data.columns.find(c => c.id === sourceColId);

            if (col && sourceNode && sourceCol) {
                constraints.push(`  CONSTRAINT "fk_${name}_${col.name}" FOREIGN KEY ("${col.name}") REFERENCES "${sourceNode.data.name}" ("${sourceCol.name}")`);
            }
        });

        return `CREATE TABLE "${name}" (\n${[...columnDefs, ...constraints].join(',\n')}\n);`;
    });

    return [
        '-- PostgreSQL Schema Generated by Schema Designer',
        dropTables,
        dropTypes,
        '',
        ...enumDefs,
        ...tables
    ].filter(Boolean).join('\n\n');
}
